version: "3.3"

services:
  database:
    build: ./database
    container_name: database
    hostname: database
    restart: always
    ports:
      - "3306:3306"
    # networks:
    #   - spring_net

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always
    # networks:
    #   - spring_net
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/UserManagement?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - database

  frontend:
    build: ./front
    ports:
      - 3003:80
   
